### ISSUE TITLE
Feedback for c3-thinking-style

### ISSUE THREAD

**Issue by kripple** [danasweet/danasweet.github.io#5]
There is so much that I love about your blog, and this post in particular. You seem like a fantastic writer (I was entertained, at least) and your layout is really pretty. I'm an AR thinker, and your post reminded me how cool it felt to realize that I was, in fact, not an idiot because I needed to work in a group to perform at my best (maybe synergy has something to do with it ..). I do wish you included a github button at the bottom, just because it would have been easier for me to find this page. Take it or leave it, but I've been using Trello.com for the last 9 weeks for my lists. I just copy-paste into a checklist at the beginning of the week. I know some others in my cohort have used Wunderlist. It's not the same as paper+pen, but it does have the advantage of durability. Hope to see you around!

**Comment by danasweet** [comment]
@kripple thanks so much! i appreciate the feedback about adding a github button--I guess I hadn't considered github a "social" network until now, but you're right, it should be there. Especially if I'm going to be using this site during my eventual employment search!

totally going to check out Trello....my current method of marking up my curriculum screenshot with paint tools is a bit outdated! hahah

Thanks again for reading and taking the time to send me your thoughts! The DBC fam is just the best!

**Comment by egermani** [comment]
Hi there! The risks of being first to complete an assignment: you'll get a lot of feedback from those of us near the front of the peloton.

Your blog post was very readable, and your writing style is relaxed. I remain impressed by the clean design you have on your blog, and wasn't surprised to read that you pay careful attention to these things.

My suggestion this week: maybe remove that thin line that sits atop the blog's post title? I like it at the bottom as a way to mark the beginning of the footer, but up underneath your nav bar there's already a clear linear separation going on, so the extra line doesn't add much.

**Comment by danasweet** [comment]
hey, thanks @egermani! I put the line under the navbar and above the footer in hopes of creating a sort of container for the blog content. i see what you mean about it being unnecessary, but it pains me to remove it for the sake of symmetry. I appreciate the feedback though, and will consider other ways to achieve what I was going for! :)
