### ISSUE TITLE
Nice blog post

### ISSUE THREAD

**Issue by mleo5555** [danasweet/danasweet.github.io#6]
Looking at your blog post made me realize I need to step up my game with css. Your post looks professionally done and is very readable unlike mine. I thought you did a great job explaining arrays and hashes to somebody who is unfamiliar with the concept. I like how you use a little bit of humor to make things light and funny while you read. I also liked the tl; dr at the end for people like myself who want a quick synopsis, might have to steal that for my future posts. Great post!

**Comment by danasweet** [comment]
thanks so much @mleo5555! to be honest, i don't see a whole lot of a difference between our websites. mine has a few more little features, which are simple enough to implement! my recommendation would be to start with a font. A small, stylistic change like that can make such a difference in a first impression!

Glad to hear that people are finding my posts funny. Sometimes its tough to try to spice up a dry subject, so I never really know how I'm coming across!

Thanks again for the feedback! And you're perfectly welcome to steal tl;dr...internet nerds gotta stick together, right?

**Comment by mleo5555** [comment]
No problem. And you are right, a few small changes would be all the
difference I just need to sit down and think about what I want my sights
blog layout to be. Internet nerds def gotta stick together hahaha
